const mainPath = '/';
export const Constants = {
    LOCATION_URL: window.location.protocol + '//' + window.location.hostname,
    // LOCATION_URL: "https://sit-tn.instantmseloans.in",
    // LOCATION_URL: "https://qa-tn.instantmseloans.in",
    IS_ENCRYPTION: true,
    cwjs: '26f1ac75f77c22ebc66e2359c13ea9955ebd5e2bd7fbe50e5b3ac2977a772302',
    httpAndCookies: {
        ACTK: 'tk_ac',
        RFTK: 'tk_rc',
        USNM: 'ur_cu',
        LGTK: 'tk_lg',
        COOKIES_OBJ: 'ck_obj',
        USERTYPE: 'usr_type',
        USER_ID: 'userId',
        ORGID: 'usr_orgId',
        ORG_NAME: 'user_org_name',
        FS_USER_ID: 'fsUserId',
        ROLEID: 'usr_role_id',
        PROFILE_ID: 'profileId',
        TMP_PROFILE_ID: 'tmpProfileId',
        CAMPIGN_CODE: 'campaignCode',
        CAMPIGN_TYPE: 'type',
        App_Count: 'applicationCount',
        VALIDATIONS: 'validations',
        FACILITATOR_ID: 'facilitatorId',
        IS_NRLM_LOGIN: 'isNrlmLogin',
        IS_ENCRYPTION: 'isEncryption',
        CAMPAIGN_DETAILS: 'campaign_details',
        BUSINESS_TYPE_ID: 'business_type_id',
        HO_BO_DASHBOARD_TAB: 'ho_bo_dashboard_tab',
        BM_FIO_DASHBOARD_TAB: 'bm_fio_dashboard_tab',
        BM_FIO_DASHBOARD_SUB_TAB: 'bm_fio_dashboard_sub_tab',
        LBM_GM_DASHBOARD_SUB_TAB: 'lbm_gm_dashboard_tab',
        BO_DASHBOARD_TAB: 'bo_dashboard_tab',
        SUPER_ADMIN_DASHBOARD_TAB: 'super_admin_dashboard_tab',
        BORROWER_USER_ID: 'borrower_user_id',
        USER_NAME: 'user_name',
        TAB_ID: 'tab_id',
        SUB_TAB_ID: 'sub_tab_id',
        All_MENU: 'all_menu',
        ACCESS_PATH: 'access_path',
        DASHBOARD_ID: 'dashboard_id',
        MAIN_DASHBOARD: 'main_dashboard',
        SCHEME_ID: 'scheme_id'
    },

    SUCCESS_MESSAGE: 'Saved Successfully',

    ROUTE_URL: {
        LOGIN: mainPath + 'login',
        HOME: mainPath + 'home',
        DISCLAIMER: mainPath + 'disclaimer',
        REGISTER: mainPath + 'signup',
        OTP_VERIFICATION: mainPath + 'otpVerfication',
        SET_PASSWORD: mainPath + 'setPassword',
        SET_PASSWORD_WEB_BANKER: mainPath + 'setPasswordWebBanker',
        DASHBOARD: mainPath + '/TIIC/Application-Status',
        CHANGE_PASSWORD: mainPath + '/ChangePassword',
        SIGNUP: mainPath + 'register',
        TIIC_BANKER_PARTNER: mainPath + '/TIIC/Bank-Partner-List',
        ADD_BANKER_PARTNER: mainPath + '/TIIC/Add-New-Bank-Partner',
        BULK_UPLOAD: mainPath + 'TIIC/Bulk-Upload',
        BULK_UPLOAD_USERS: mainPath + '/TIIC/BulkUpload-User',
        BULK_UPLOAD_FIO: mainPath + '/TIIC/BulkUpload-Fio',
        HO_BO_DATA_FILEDS: mainPath + 'TIIC/Com-DataFields',
        TIIC_FIELD_INSPECTION_LIST: mainPath + '/TIIC/FieldInspection-List',
        FIO_LIST: mainPath + '/TIIC/BMFIO-List',
        FIO_FORM: mainPath + '/TIIC/BMFIO-Form',
        TIIC_FIELD_INSPECTION_FORM: mainPath + '/TIIC/FieldInspection-Form',
        BO_DASHBOARD: mainPath + '/TIIC/Dashboard-List',
        ALL_USER_LIST: mainPath + '/TIIC/AllUser-List',
        ALL_OFFICE_LIST: mainPath + '/TIIC/AllOffice-List',
        ADD_OR_UPDATE_USER: mainPath + '/TIIC/newUserCreate',
        ADD_OR_UPDATE_BRANCH: mainPath + '/TIIC/newBranchCreate',
        BRANCH_UPLOAD_USER: mainPath + '/TIIC/BulkUpload-User',
        BULK_UPLOAD_BRANCH_OFC: mainPath + '/TIIC/BulkUpload-Office',
        BANKER_DASHBOARD: mainPath + 'dashboards/Dashboard',
        BMFIOS_LOAN_APPLICATION_LIST: mainPath + 'TIIC/BMFIOS-LoanApplication',
        BMFIOS_LOAN_APPLICATION_VIEW: mainPath + 'TIIC/BMFIOS-LoanApplicationView',
        COMMITTEE_LOAN_APPLICATION_VIEW: mainPath + 'TIIC/Committee-LoanApplication',
        SUPPORT_DASHBOARD: mainPath + 'TIIC/supportDashboard',
        DISBURSMENT_CERTIFICATE: mainPath + 'TIIC/DisbursmentCertificate',

    },

    validationModule: {
        REGISTER: "registered",
        LOGIN: "login",
        NEW_BANK_PARTNER: "NewBankPartner",
        FIELD_INSPECTION_FORM: "FieldInspectionForm",
        HOBO_DATA_FIELDS: "HoBoDataFields",
        FIO_BM_DATA_FIELDS: "FioBmDataFields",
        PRE_SANCTION_DETAILS: "PreSanctionDetails",
        PRE_SANCTION_MEMO_DETAILS: "PreSanctionMemoDetails",
        PRE_SCREENING_DETAILS: "PreScreeningDetails",
        BRANCH_MANAGER_REMARKS: "BranchManagerRemarks",
        SANCTION_LETTER_DETAILS: "SanctionLetterDetails",
        SANCTION_DETAILS: "SanctionDetails",
    },


    StatusMaster: {
        PENDING: { id: 1, name: 'Pending' },
        FETCHED: { id: 2, name: 'Fetched' },
        ERROR: { id: 3, name: 'Error' },
        COMPLETED: { id: 4, name: 'Completed' }
    },

    UserType: {
        BORROWER: 1,
        OTHER_USERS: 2,
        SUPER_ADMIN: 3,
        SUPPORT: 4,
    },
    UserTypeList: [
        { id: 3, name: 'Super Admin' },
        { id: 2, name: 'Other Users' },
        { id: 4, name: 'Support' },
    ],

    RoleMaster: [
        { id: 1, name: 'Super Admin' },
        { id: 2, name: 'Admin Maker' },
        { id: 3, name: 'Admin Checker' },
        { id: 4, name: 'Branch Manager' },
        { id: 5, name: 'Bank BO' },
        { id: 6, name: 'Bank HO' },
        { id: 7, name: 'Bank ZO' },
        { id: 8, name: 'Field Inspection Officers' },
        { id: 10, name: 'Lead Bank Managers' },
        { id: 11, name: 'General Managers' },
        { id: 12, name: 'Support' }
        // { id: 17, name: 'Super Admin' },
        // { id: 18, name: 'Product Maker' },
        // { id: 19, name: 'Product Checker' },
        // { id: 20, name: 'Admin User' },
        // { id: 21, name: 'Field Inspection Officer' }
    ],
    UserRoleList: {
        SUPER_ADMIN: { id: 1, name: 'Super Admin' },
        ADMIN_MAKER: { id: 2, name: 'Admin Maker' },
        ADMIN_CHECKER: { id: 3, name: 'Admin Checker' },
        BRANCH_MANAGER: { id: 4, name: 'Branch Manager' },
        BANK_BO: { id: 5, name: 'Bank BO' },
        BANK_HO: { id: 6, name: 'Bank HO' },
        BANK_ZO: { id: 7, name: 'Bank ZO' },
        FIELD_INSPECTION_OFFICER: { id: 8, name: 'Field Inspection Officer' },
        LEAD_BANK_MANAGER: { id: 10, name: 'Lead Bank Manager' },
        GENERAL_MANAGER: { id: 11, name: 'General Manager' },
        SUPPORT: { id: 12, name: 'Support' }
        // CARE_SUPER_ADMIN: { id: 17, name: 'Super Admin' },
        // CARE_PRODUCT_MAKER: { id: 18, name: 'Product Maker' },
        // CARE_PRODUCT_CHECKER: { id: 19, name: 'Product Checker' },
        // CARE_ADMIN_USER: { id: 20, name: 'Admin User' },
        // CARE_FIO: { id: 21, name: 'Field Inspection Officer' }
    },

    tabMasterList: [
        { id: 1, name: 'All User' },
        { id: 2, name: 'Bank Partner' },
        { id: 3, name: 'Admin User' },
        { id: 4, name: 'Field Inspection Officer' },
        { id: 5, name: 'Lead Bank Manager' },
        { id: 6, name: 'General Manager' },
        { id: 7, name: 'Branch manager' },
        // { id: 8, name: 'Product User' },
    ],
    tabMaster: {
        ALL_USER: { id: 1, name: 'All User' },
        BANK_PARTNER: { id: 2, name: 'Bank Partner' },
        ADMIN_USER: { id: 3, name: 'Admin User' },
        FIELD_INSPECTION_OFFICER: { id: 4, name: 'Field Inspection Officer' },
        LEAD_BANK_MANAGER: { id: 5, name: 'Lead Bank Manager' },
        GENERAL_MANAGER: { id: 6, name: 'General Manager' },
        BRANCH_MANAGER: { id: 7, name: 'Branch Manager' }
        // PRODUCT_USER: { id: 8, name: 'Product User' }
    },

    departmentList: [
        { id: 301, name: 'TIIC' },
        { id: 302, name: 'TAICO' },
        { id: 303, name: 'DIC' },
        { id: 304, name: 'ICDIC' },
        { id: 305, name: 'TNCGS' }
    ],
    department: {
        TIIC: { id: 301, name: 'TIIC' },
        TAICO: { id: 302, name: 'TAICO' },
        DIC: { id: 303, name: 'DIC' },
        ICDIC: { id: 304, name: 'ICDIC' },
        TNCGS: { id: 305, name: 'TNCGS' }
    },

    adminUserList: [
        { id: 2, name: 'Admin Maker' },
        { id: 3, name: 'Admin Checker' }
    ],
    workflow: {
        step: {
            HO_FORM_DETAILS: { id: 1, value: "Bank HO Details Fill" },
            BO_FORM_DETAILS: { id: 2, value: "Bank BO Details Fill" },
            FIO_FORM_DETAILS: { id: 3, value: "FIO form details" },
            BM_FORM_DETAILS: { id: 4, value: "BM form details" },
            PSF_FIO: { id: 21, value: "FIO Pre-Sanction flow" },
            PSF_BM: { id: 22, value: "BM Pre-Sanction flow" },
            PSF_BM_SCHEDULE_MEETING: { id: 23, value: "BM Schedule meeting" },
            PSF_BM_COMPLETED: { id: 29, value: "BM Meeting completed" },
            PSF_LBM_RECO: { id: 32, value: "LBM Recommandetion" },
            PSF_GM_RECO: { id: 33, value: "GM Recommandetion" },
            PSF_BM_RECO: { id: 35, value: "BM Recommandetion" },
            PSF_BM_E_SIGN: { id: 20, value: "BM E-Sign" },
            PSF_LBM_E_SIGN: { id: 36, value: "LBM E-Sign" },
            PSF_GM_E_SIGN: { id: 37, value: "GM E-Sign" },
            PSF_BM_SANCTION_HOLD_REJECT: { id: 24, value: "BM Sanction hold reject" },
            PSF_BM_HOLD: { id: 26, value: "BM Hold" },
            PSF_BM_REJECT: { id: 25, value: "BM Reject" },
            SF_FIO: { id: 31, value: "FIO Santion" },
            SF_BM: { id: 27, value: "BM Sanction" },
            BM_DISBURSE: { id: 30, value: "Disburse" },
        },
        action: {
            SEND_TO_BO: { id: 1, value: 'Send to bo' },
            SUBMIT: { id: 2, value: 'Submit to fio' },
            SEND_BACK: { id: 3, value: 'Send back' },
            POSITIVE: { id: 4, value: 'Send to tiic BM from Tiic FO' },
            FIO_SAVE: { id: 6, value: 'Save' },
            NEGATIVE: { id: 7, value: 'Mark as Negative ' },
            APPROVED: { id: 8, value: 'Approved by BM ' },
            SEND_TO_BM: { id: 9, value: 'Send to BM' },
            SAVE: { id: 10, value: 'Save' },
            REJECT: { id: 25, value: 'Reject' },
            SEND_BACK_TO_FIO: { id: 26, value: 'Send back to FIO' },
            APPROVE: { id: 27, value: 'Approve ' },
            E_SIGN: { id: 28, value: 'E-Sign Penging' },
            TRANSFER: { id: 24, value: 'Transfer' },
        },
        sanctionFlowActions: {
            PSF_SEND_FOR_APPROVAL: { id: 30, value: 'Send for Approval' },
            PSF_SEND_BACK: { id: 31, value: 'Sent back' },
            PSF_APPROVED: { id: 32, value: 'Approved' },
            SCHEDULE_MEETTING: { id: 33, value: 'Schedule Meeting' },
            COMPLETED_MEETTING: { id: 34, value: 'Meeting Completed' },
            LBM_RECO: { id: 43, value: 'Give Recoomendation' },
            GM_RECO: { id: 43, value: 'Give Recoomendation' },
            BM_RECO: { id: 43, value: 'Give Recoomendation' },
            BM_E_SIGN: { id: 28, value: 'E-Sign' },
            LBM_E_SIGN: { id: 28, value: 'E-Sign' },
            GM_E_SIGN: { id: 28, value: 'E-Sign' },
            PSF_SANCTION: { id: 37, value: 'E-Sign' },
            PSF_HOLD: { id: 36, value: 'E-Sign' },
            PSF_REJECT: { id: 35, value: 'E-Sign' },
            SF_SEND_FOR_APPROVAL: { id: 30, value: 'Send for Approval' },
            SF_SEND_BACK: { id: 40, value: 'Sent back' },
            SF_APPROVED: { id: 32, value: 'Approved' },
            DISBURSE: { id: 42, value: 'Disburse' },
        }
    },

    userMgmtColumns: {
        USER_NAME: { id: 1, name: 'userName' },
        ROLE: { id: 2, name: 'role' },
        EMAIL: { id: 3, name: 'email' },
        MOBILE: { id: 4, name: 'mobile' },
        ORG: { id: 5, name: 'org' },
        DEPARTMENT: { id: 6, name: 'department' },
        DISTRICT: { id: 7, name: 'district' },
        BRANCHNAME: { id: 8, name: 'branchName' },
        CITY: { id: 9, name: 'city' },
        STATUS: { id: 10, name: 'status' },
        ISVIEW: { id: 11, name: 'isView' },
        ISEDIT: { id: 12, name: 'isEdit' },
        ISLOCK: { id: 13, name: 'isLock' },
        RESET_PASSWORD: { id: 14, name: 'resetPassword' }
    },
    productStatus: [
        { id: 1, name: 'Active' },
        { id: 2, name: 'Saved' },
        { id: 3, name: 'Send to Checker' },
        { id: 4, name: 'Sent Back To Maker' },
        { id: 5, name: 'InActive' },
        { id: 6, name: 'Activation Request' },
        { id: 7, name: 'Deactvation Request' },
        { id: 8, name: 'Modification' },
    ],
    ScoringStatusNew: {
        SAVED: 1,
        SEND_TO_CHECKER: 2,
        APPROVED: 3,
        SEND_BACK_BY_CHECKER: 4,
        ACTIVATION_REQUEST: 5,
        DEACTIVATION_REQUEST: 6
    },
    ScoringStatus: [
        { code: 'SAVED', name: 'SAVED', id: 1 },
        { code: 'SEND_TO_CHECKER', name: 'SEND TO CHECKER', id: 2 },
        { code: 'APPROVED', name: 'APPROVED', id: 3 },
        { code: 'SEND_BACK_BY_CHECKER', name: 'SEND BACK BY CHECKER', id: 4 },
        { code: 'ACTIVATION_REQUEST', name: 'ACTIVATION REQUEST', id: 5 },
        { code: 'DEACTIVATION_REQUEST', name: 'DEACTIVATION REQUEST', id: 6 }
    ],
    AddressType: {
        LOCAL: 1,
        LDG: 2
    },

    FioBmStatusMaster: [
        { id: 10, name: 'New Application', fioDisplayName: 'New Application', bmDisplayName: 'New Application', isDisplay: true },
        { id: 11, name: 'In-Progress', fioDisplayName: 'In-Progress', bmDisplayName: 'In-Progress', isDisplay: true },
        { id: 12, name: 'Send back to FIO', fioDisplayName: 'Received from BM', bmDisplayName: 'Send back to FIO', isDisplay: true },
        { id: 14, name: 'Positive', fioDisplayName: 'Sent to BM for Approval', bmDisplayName: 'Received From FIO For Approval', isDisplay: true },
        { id: 15, name: 'Negative', fioDisplayName: 'Sent to BM for Approval', bmDisplayName: 'Received From FIO For Approval', isDisplay: false },
        { id: 16, name: 'Send Back By FIO', fioDisplayName: 'Sent Back to BM', bmDisplayName: 'Send Back By FIO', isDisplay: true },
        { id: 17, name: 'E-sign Pending', fioDisplayName: 'E-sign Pending', bmDisplayName: 'E-sign Pending', isDisplay: true },
        { id: 18, name: 'E-sign Completed', fioDisplayName: 'E-sign Completed', bmDisplayName: 'E-sign Completed', isDisplay: true },
        { id: 19, name: 'Reject', fioDisplayName: 'Reject', bmDisplayName: 'Reject', isDisplay: true },
        { id: 20, name: 'Approve', fioDisplayName: 'Approve', bmDisplayName: 'Approve', isDisplay: true },
        { id: 21, name: 'Transfer', fioDisplayName: 'Transfered By ', bmDisplayName: 'Transfered By ', isDisplay: true }
    ],

    ApplicationStatusMaster: {
        NEW_APPLICATION: 10,
        IN_PROGRESS: 11,
        SEND_BACK_TO_FIO: 12,
        POSITIVE: 14,
        NEGATIVE: 15,
        SEND_TO_BM: 16,
        E_SIGN_PENDING: 17,
        E_SIGN_COMPLETED: 18,
        REJECTED_BY_BM: 19,
        APPROVED_BY_BM: 20,
        TRANSFERED_BY_BRANCH: 21,
        SF_SANCTIONED: 14,
    },

    PROPOSAL_STATUS: {
        SANCTION: 2,
        HOLD: 5,
        REJECT: 4,
        DISBURSED: 3,
    },

    DASHBOARD_LIST: [
        { id: 1, name: 'Field Inspection' }, // , path: mainPath + 'TIIC'
        { id: 2, name: 'Sanction', }, // path: mainPath + 'TIIC'
    ],

    SanctionDashboardStatusMaster: [
        { id: 1, name: 'New Application', fioDisplayName: 'New Application', bmDisplayName: 'New Application', lbmDisplayName: undefined, gmDisplayName: undefined, fioTab: 7, bmTab: 2, lbmTab: undefined, gmTab: undefined },
        { id: 2, name: 'In-Progress', fioDisplayName: 'In-Progress', bmDisplayName: 'In-Progress', lbmDisplayName: undefined, gmDisplayName: undefined, fioTab: 7, bmTab: 2, lbmTab: undefined, gmTab: undefined },
        { id: 3, name: 'Sent for Approval', fioDisplayName: undefined, bmDisplayName: 'Received for Approval', lbmDisplayName: undefined, gmDisplayName: undefined, fioTab: undefined, bmTab: 7, lbmTab: undefined, gmTab: undefined },
        { id: 4, name: 'Received from BM', fioDisplayName: 'Received from BM', bmDisplayName: 'Send back to FIO', lbmDisplayName: undefined, gmDisplayName: undefined, fioTab: 7, bmTab: 2, lbmTab: undefined, gmTab: undefined },
        { id: 5, name: 'Approved', fioDisplayName: undefined, bmDisplayName: 'Meeting Pending', lbmDisplayName: undefined, gmDisplayName: undefined, fioTab: undefined, bmTab: 7, lbmTab: undefined, gmTab: undefined },
        { id: 6, name: 'Meeting scheduled', fioDisplayName: undefined, bmDisplayName: 'Meeting scheduled', lbmDisplayName: undefined, gmDisplayName: undefined, fioTab: undefined, bmTab: 2, lbmTab: undefined, gmTab: undefined },
        { id: 7, name: 'Meeting Compeleted', fioDisplayName: undefined, bmDisplayName: 'Recommendation Pending (LBM)', lbmDisplayName: 'Recommendation Pending', gmDisplayName: undefined, fioTab: undefined, bmTab: 2, lbmTab: 2, gmTab: undefined },
        { id: 8, name: 'Recommendation Done (LBM)', fioDisplayName: undefined, bmDisplayName: 'Recommendation Pending (GM)', lbmDisplayName: undefined, gmDisplayName: 'Recommendation Pending', fioTab: undefined, bmTab: 2, lbmTab: undefined, gmTab: 2 },
        { id: 9, name: 'Recommendation Done (GM)', fioDisplayName: undefined, bmDisplayName: 'Recommendation Pending (BM)', lbmDisplayName: undefined, gmDisplayName: undefined, fioTab: undefined, bmTab: 2, lbmTab: undefined, gmTab: undefined },
        { id: 10, name: 'Recommendation Done (BM)', fioDisplayName: undefined, bmDisplayName: 'Digital Signature Pending (BM)', lbmDisplayName: undefined, gmDisplayName: undefined, fioTab: undefined, bmTab: 7, lbmTab: undefined, gmTab: undefined },
        { id: 10, name: 'Recommendation Done (BM)', fioDisplayName: undefined, bmDisplayName: 'Digital Signature Pending (BM)', lbmDisplayName: undefined, gmDisplayName: undefined, fioTab: undefined, bmTab: 8, lbmTab: undefined, gmTab: undefined },
        { id: 10, name: 'Recommendation Done (BM)', fioDisplayName: undefined, bmDisplayName: 'Digital Signature Pending (BM)', lbmDisplayName: undefined, gmDisplayName: undefined, fioTab: undefined, bmTab: 2, lbmTab: undefined, gmTab: undefined },
        { id: 11, name: 'Digital Signature Done (BM)', fioDisplayName: undefined, bmDisplayName: 'Digital Signature Pending (LBM)', lbmDisplayName: 'Digital Signature Pending', gmDisplayName: undefined, fioTab: undefined, bmTab: 7, lbmTab: 2, gmTab: undefined },
        { id: 11, name: 'Digital Signature Done (BM)', fioDisplayName: undefined, bmDisplayName: 'Digital Signature Pending (LBM)', lbmDisplayName: undefined, gmDisplayName: undefined, fioTab: undefined, bmTab: 2, lbmTab: undefined, gmTab: undefined },
        { id: 12, name: 'Digital Signature Done (LBM)', fioDisplayName: undefined, bmDisplayName: 'Digital Signature Pending (GM)', lbmDisplayName: undefined, gmDisplayName: 'Digital Signature Pending', fioTab: undefined, bmTab: 7, lbmTab: undefined, gmTab: 2 },
        { id: 12, name: 'Digital Signature Done (LBM)', fioDisplayName: undefined, bmDisplayName: 'Digital Signature Pending (GM)', lbmDisplayName: undefined, gmDisplayName: undefined, fioTab: undefined, bmTab: 2, lbmTab: undefined, gmTab: undefined },
        { id: 13, name: 'Digital Signature Done (GM)', fioDisplayName: 'In-Progress', bmDisplayName: 'Proposal Pending for Sanction', lbmDisplayName: undefined, gmDisplayName: undefined, fioTab: 8, bmTab: 7, lbmTab: undefined, gmTab: undefined },
        { id: 13, name: 'Digital Signature Done (GM)', fioDisplayName: 'Pending for Sanction', bmDisplayName: 'Digital Signature Pending', lbmDisplayName: undefined, gmDisplayName: undefined, fioTab: 2, bmTab: undefined, lbmTab: undefined, gmTab: undefined },
        { id: 14, name: 'Sanctioned', fioDisplayName: 'In-Process ', bmDisplayName: 'Proposal Pending for Disburse', lbmDisplayName: undefined, gmDisplayName: undefined, fioTab: 8, bmTab: undefined, lbmTab: undefined, gmTab: undefined },
        { id: 15, name: 'Send for Approval', fioDisplayName: 'Sent for Approval', bmDisplayName: 'Received for Approval', lbmDisplayName: undefined, gmDisplayName: undefined, fioTab: 2, bmTab: 8, lbmTab: undefined, gmTab: undefined },
        { id: 15, name: 'Send for Approval', fioDisplayName: 'Sent for Approval', bmDisplayName: 'New Application', lbmDisplayName: undefined, gmDisplayName: undefined, fioTab: 3, bmTab: 3, lbmTab: undefined, gmTab: undefined },
        { id: 16, name: 'Send Back', fioDisplayName: 'Received from Branch Manager', bmDisplayName: 'Send Back to FIO', lbmDisplayName: undefined, gmDisplayName: undefined, fioTab: 8, bmTab: 3, lbmTab: undefined, gmTab: undefined },
        { id: 17, name: 'Approved', fioDisplayName: 'Pending for Disburse', bmDisplayName: 'Proposal Pending for Disburse', lbmDisplayName: undefined, gmDisplayName: undefined, fioTab: 3, bmTab: 8, lbmTab: undefined, gmTab: undefined },
        { id: 18, name: 'Disbursed', fioDisplayName: undefined, bmDisplayName: 'Digital Signature Pending', lbmDisplayName: undefined, gmDisplayName: undefined, fioTab: undefined, bmTab: undefined, lbmTab: undefined, gmTab: undefined },
        { id: 19, name: 'Reject', fioDisplayName: undefined, bmDisplayName: 'Digital Signature Pending', lbmDisplayName: undefined, gmDisplayName: undefined, fioTab: undefined, bmTab: undefined, lbmTab: undefined, gmTab: undefined },
        { id: 20, name: 'Hold', fioDisplayName: undefined, bmDisplayName: 'Proposal Pending for Disburse', lbmDisplayName: undefined, gmDisplayName: undefined, fioTab: undefined, bmTab: undefined, lbmTab: undefined, gmTab: undefined },
        { id: 20, name: 'Borrower', fioDisplayName: undefined, bmDisplayName: 'Digital Signature Pending (Borrower)', lbmDisplayName: undefined, gmDisplayName: undefined, fioTab: undefined, bmTab: 3, lbmTab: undefined, gmTab: undefined },
    ],

    SanctionDashboardPendingWithMaster: [
        { id: 1, name: 'BM', fioDisplayName: 'Branch Manager', bmDisplayName: 'Branch Manager', bmTab: 2, fioTab: 2 },
        { id: 2, name: 'BM', fioDisplayName: 'Branch Manager', bmDisplayName: 'Branch Manager', bmTab: undefined, fioTab: 3 },
        { id: 3, name: 'FIO', fioDisplayName: 'FIO', bmDisplayName: 'Field Inspection Officer', bmTab: 2, fioTab: undefined },
        { id: 4, name: 'LBM', fioDisplayName: 'Lead Bank Manager', bmDisplayName: 'Lead Bank Manager', bmTab: 2, fioTab: undefined },
        { id: 5, name: 'GM', fioDisplayName: 'General Manager', bmDisplayName: 'General Manager', bmTab: 2, fioTab: undefined },
        { id: 6, name: 'FIO', fioDisplayName: 'Field Inspection Officer', bmDisplayName: 'Field Inspection Officer', bmTab: 3, fioTab: undefined },
        { id: 7, name: 'Borrower', fioDisplayName: 'Borrower', bmDisplayName: 'Borrower', bmTab: 3, fioTab: undefined },
    ],

    REGEX_TYPE: [
        { id: 1, value: /[^0-9]/g, desc: 'Number Only' },
        { id: 2, value: /[^A-Za-z]/g, desc: 'Alphabetic Only' },
        { id: 3, value: /[^A-Za-z0-9]/g, desc: 'Alphanumeric Only' },
        { id: 4, value: /[^a-zA-Z\s]/g, desc: 'Alphabetic With Space Only' },
        { id: 5, value: /[^A-Za-z0-9\s]/g, desc: 'Alphanumeric With Space Only' },
        { id: 6, value: /[\s]/g, desc: 'No-Space Only' },
        { id: 7, value: /[^0-9\s]/g, desc: 'Numeric and Space Only' },
        { id: 8, value: /[^0-9.]/g, desc: 'Number with Decimal Only' },
    ],

    SchemeMaster: {
        ALL_SCHEME: { id: -1, name: "All Scheme", code: "All", businessTypeId: -1 },
        TNCGS: { id: 1, name: "TNCGS", code: "TNCGS", businessTypeId: 1 },
        CARE: { id: 2, name: "CARE", code: "CARE", businessTypeId: 1 }
    },
    schemeList: [
        { id: -1, name: 'All Scheme', code: 'All' },
        { id: 1, name: 'TNCGS', code: 'TNCGS' },
        { id: 2, name: 'CARE', code: 'CARE' }
    ],

    // setJSON: {
    //     "firstName": "dfgfg",
    //     "middleName": "fghfgh",
    //     "lastName": "ghgh",
    //     "mobile": "6676786867",
    //     "email": "ravi@opl.com",
    //     "isActive": true,
    //     "isEditMode": false,
    //     "selectedScheme": [
    //         2
    //     ]
    // }
};

