const customersData = [
    {
        Id: '1',
        ProductName: 'Contactless Loan GST based invoice financing',
        ProductType: 'Working Capital Term Loan',
        Version: 'V 0.1',
        LastModified: '24 march 2020 04:35 PM',
        RequestType: 'New Product'
    },
    {
        Id: '2',
        ProductName: 'Contactless Loan GST based invoice financing',
        ProductType: 'Working Capital Term Loan',
        Version: 'V 0.1',
        LastModified: '24 march 2020 04:35 PM',
        RequestType: 'Deactivation Requested'

    },
    {
        Id: '3',
        ProductName: 'Contactless Loan GST based invoice financing',
        ProductType: 'Working Capital Term Loan',
        Version: 'V 0.1',
        LastModified: '24 march 2020 04:35 PM',
        RequestType: 'Activation Requested'
    },
    {
        Id: '4',
        ProductName: 'Contactless Loan GST based invoice financing',
        ProductType: 'Working Capital Term Loan',
        Version: 'V 0.1',
        LastModified: '24 march 2020 04:35 PM',
        RequestType: 'Modification'
    }
];

const liveMonitorData = [
    {
        Id: '1',
        BorrowerName: 'VM Shah & Co.',
        ApplicationID: 'CW-ALT-11599-10014613',
        TotalDisbursedAmount: '₹ 1,00,00,000',
        Sales: '2.2 %',
        BankStatementCredit: '2.2 %',
        Chequeissuedbounced: '2.2 %',
        MarketValueOfEligibleStocks: '0.0 %',
        MarketValueOfEligibleDebtors: '2.2 %',
        Source: 'Disbursed through platform',
        LastUpdatedOn: '22-Jul-20',
        IconTrendingUp: 'trending-up',
        IconTrendingDown: 'trending-down',
        IconTrendingFlat: 'trending-flat',
    },
    {
        Id: '2',
        BorrowerName: 'VM Shah & Co.',
        ApplicationID: 'CW-ALT-11599-10014613',
        TotalDisbursedAmount: '₹ 1,00,00,000',
        Sales: '2.2 %',
        BankStatementCredit: '2.2 %',
        Chequeissuedbounced: '2.2 %',
        MarketValueOfEligibleStocks: '0.0 %',
        MarketValueOfEligibleDebtors: '2.2 %',
        Source: 'Disbursed through platform',
        LastUpdatedOn: '22-Jul-20',
        IconTrendingUp: 'trending-up',
        IconTrendingDown: 'trending-down',
        IconTrendingFlat: 'trending-flat',
    },
    {
        Id: '3',
        BorrowerName: 'VM Shah & Co.',
        ApplicationID: 'CW-ALT-11599-10014613',
        TotalDisbursedAmount: '₹ 1,00,00,000',
        Sales: '2.2 %',
        BankStatementCredit: '2.2 %',
        Chequeissuedbounced: '2.2 %',
        MarketValueOfEligibleStocks: '0.0 %',
        MarketValueOfEligibleDebtors: '2.2 %',
        Source: 'Disbursed through platform',
        LastUpdatedOn: '22-Jul-20',
        IconTrendingUp: 'trending-up',
        IconTrendingDown: 'trending-down',
        IconTrendingFlat: 'trending-flat',
    },
    {
        Id: '4',
        BorrowerName: 'VM Shah & Co.',
        ApplicationID: 'CW-ALT-11599-10014613',
        TotalDisbursedAmount: '₹ 1,00,00,000',
        Sales: '2.2 %',
        BankStatementCredit: '2.2 %',
        Chequeissuedbounced: '2.2 %',
        MarketValueOfEligibleStocks: '0.0 %',
        MarketValueOfEligibleDebtors: '2.2 %',
        Source: 'Disbursed through platform',
        LastUpdatedOn: '22-Jul-20',
        IconTrendingUp: 'trending-up',
        IconTrendingDown: 'trending-down',
        IconTrendingFlat: 'trending-flat',
    },
    {
        Id: '5',
        BorrowerName: 'VM Shah & Co.',
        ApplicationID: 'CW-ALT-11599-10014613',
        TotalDisbursedAmount: '₹ 1,00,00,000',
        Sales: '2.2 %',
        BankStatementCredit: '2.2 %',
        Chequeissuedbounced: '2.2 %',
        MarketValueOfEligibleStocks: '0.0 %',
        MarketValueOfEligibleDebtors: '2.2 %',
        Source: 'Disbursed through platform',
        LastUpdatedOn: '22-Jul-20',
        IconTrendingUp: 'trending-up',
        IconTrendingDown: 'trending-down',
        IconTrendingFlat: 'trending-flat',
    },
    {
        Id: '6',
        BorrowerName: 'VM Shah & Co.',
        ApplicationID: 'CW-ALT-11599-10014613',
        TotalDisbursedAmount: '₹ 1,00,00,000',
        Sales: '2.2 %',
        BankStatementCredit: '2.2 %',
        Chequeissuedbounced: '2.2 %',
        MarketValueOfEligibleStocks: '0.0 %',
        MarketValueOfEligibleDebtors: '2.2 %',
        Source: 'Disbursed through platform',
        LastUpdatedOn: '22-Jul-20',
        IconTrendingUp: 'trending-up',
        IconTrendingDown: 'trending-down',
        IconTrendingFlat: 'trending-flat',
    },
    {
        Id: '7',
        BorrowerName: 'VM Shah & Co.',
        ApplicationID: 'CW-ALT-11599-10014613',
        TotalDisbursedAmount: '₹ 1,00,00,000',
        Sales: '2.2 %',
        BankStatementCredit: '2.2 %',
        Chequeissuedbounced: '2.2 %',
        MarketValueOfEligibleStocks: '0.0 %',
        MarketValueOfEligibleDebtors: '2.2 %',
        Source: 'Disbursed through platform',
        LastUpdatedOn: '22-Jul-20',
        IconTrendingUp: 'trending-up',
        IconTrendingDown: 'trending-down',
        IconTrendingFlat: 'trending-flat',
    },
    {
        Id: '8',
        BorrowerName: 'VM Shah & Co.',
        ApplicationID: 'CW-ALT-11599-10014613',
        TotalDisbursedAmount: '₹ 1,00,00,000',
        Sales: '2.2 %',
        BankStatementCredit: '2.2 %',
        Chequeissuedbounced: '2.2 %',
        MarketValueOfEligibleStocks: '0.0 %',
        MarketValueOfEligibleDebtors: '2.2 %',
        Source: 'Disbursed through platform',
        LastUpdatedOn: '22-Jul-20',
        IconTrendingUp: 'trending-up',
        IconTrendingDown: 'trending-down',
        IconTrendingFlat: 'trending-flat',
    },
    {
        Id: '9',
        BorrowerName: 'VM Shah & Co.',
        ApplicationID: 'CW-ALT-11599-10014613',
        TotalDisbursedAmount: '₹ 1,00,00,000',
        Sales: '2.2 %',
        BankStatementCredit: '2.2 %',
        Chequeissuedbounced: '2.2 %',
        MarketValueOfEligibleStocks: '0.0 %',
        MarketValueOfEligibleDebtors: '2.2 %',
        Source: 'Disbursed through platform',
        LastUpdatedOn: '22-Jul-20',
        IconTrendingUp: 'trending-up',
        IconTrendingDown: 'trending-down',
        IconTrendingFlat: 'trending-flat',
    },
    {
        Id: '10',
        BorrowerName: 'VM Shah & Co.',
        ApplicationID: 'CW-ALT-11599-10014613',
        TotalDisbursedAmount: '₹ 1,00,00,000',
        Sales: '2.2 %',
        BankStatementCredit: '2.2 %',
        Chequeissuedbounced: '2.2 %',
        MarketValueOfEligibleStocks: '0.0 %',
        MarketValueOfEligibleDebtors: '2.2 %',
        Source: 'Disbursed through platform',
        LastUpdatedOn: '22-Jul-20',
        IconTrendingUp: 'trending-up',
        IconTrendingDown: 'trending-down',
        IconTrendingFlat: 'trending-flat',
    },
    {
        Id: '11',
        BorrowerName: 'VM Shah & Co.',
        ApplicationID: 'CW-ALT-11599-10014613',
        TotalDisbursedAmount: '₹ 1,00,00,000',
        Sales: '2.2 %',
        BankStatementCredit: '2.2 %',
        Chequeissuedbounced: '2.2 %',
        MarketValueOfEligibleStocks: '0.0 %',
        MarketValueOfEligibleDebtors: '2.2 %',
        Source: 'Disbursed through platform',
        LastUpdatedOn: '22-Jul-20',
        IconTrendingUp: 'trending-up',
        IconTrendingDown: 'trending-down',
        IconTrendingFlat: 'trending-flat',
    },
];

const Disbursedthroughplatform = [
    {
        Id: '1',
        BorrowerName: 'VM Shah & Co.',
        ApplicationID: 'CW-ALT-11599-10014613',
        PAN: 'HNYPS9340P',
        TypeOfFacility: 'Working Capital',
        Total_Disbursed: '₹ 1,00,00,000',
        AmountTillNow: '₹ 50,00,000',
        FirstDisbursement: '04 April 2020 ',
        LastDisbursement: '04 June 2020 %',
        BranchName: 'Navrangpura ',
        BranchCode: '0002051',
        BranchCity: 'Ahmedabad',
        BranchState: 'Gujarat',
    },
    {
        Id: '2',
        BorrowerName: 'VM Shah & Co.',
        ApplicationID: 'CW-ALT-11599-10014613',
        PAN: 'HNYPS9340P',
        TypeOfFacility: 'Working Capital',
        Total_Disbursed: '₹ 1,00,00,000',
        AmountTillNow: '₹ 50,00,000',
        FirstDisbursement: '04 April 2020 ',
        LastDisbursement: '04 June 2020 %',
        BranchName: 'Navrangpura ',
        BranchCode: '0002051',
        BranchCity: 'Ahmedabad',
        BranchState: 'Gujarat',
    },
    {
        Id: '3',
        BorrowerName: 'VM Shah & Co.',
        ApplicationID: 'CW-ALT-11599-10014613',
        PAN: 'HNYPS9340P',
        TypeOfFacility: 'Working Capital',
        Total_Disbursed: '₹ 1,00,00,000',
        AmountTillNow: '₹ 50,00,000',
        FirstDisbursement: '04 April 2020 ',
        LastDisbursement: '04 June 2020 %',
        BranchName: 'Navrangpura ',
        BranchCode: '0002051',
        BranchCity: 'Ahmedabad',
        BranchState: 'Gujarat',
    },
];

const AddedBorrowersHistory = [
    {
        Id: '1',
        FileName: 'NavrangpuraMonitoring.xlsx',
        UploadedOn: '20-May-2020',
        SuccessfulEntries: '420',
        FailedEntries: '85',
        TotalEntries: '505',
    },
    {
        Id: '2',
        FileName: 'NavrangpuraMonitoring.xlsx',
        UploadedOn: '20-May-2020',
        SuccessfulEntries: '420',
        FailedEntries: '85',
        TotalEntries: '505',
    },
    {
        Id: '3',
        FileName: 'NavrangpuraMonitoring.xlsx',
        UploadedOn: '20-May-2020',
        SuccessfulEntries: '420',
        FailedEntries: '85',
        TotalEntries: '505',
    },
];

const RequestsFromBorrower = [
    {
        Id: '1',
        BorrowerName: 'VM Shah & Co.',
        PAN: 'HNYPS9340P',
        EmailID: 'vmshah@gmail.com',
        MobileNumber: '8295796995',
        TypeOfFacility: 'Working Capital',
        TotalDisbursedAmount: '₹ 1,00,00,000',
        DateOfFirstDisbursement: '05-June-20',
        BranchName: 'Navrangpura',
        BranchCode: '0002051',
        DateOfRequest: '04-June-2020'
    },
    {
        Id: '2',
        BorrowerName: 'VM Shah & Co.',
        PAN: 'HNYPS9340P',
        EmailID: 'vmshah@gmail.com',
        MobileNumber: '8295796995',
        TypeOfFacility: 'Working Capital',
        TotalDisbursedAmount: '₹ 1,00,00,000',
        DateOfFirstDisbursement: '05-June-20',
        BranchName: 'Navrangpura',
        BranchCode: '0002051',
        DateOfRequest: '04-June-2020'
    }, {
        Id: '3',
        BorrowerName: 'VM Shah & Co.',
        PAN: 'HNYPS9340P',
        EmailID: 'vmshah@gmail.com',
        MobileNumber: '8295796995',
        TypeOfFacility: 'Working Capital',
        TotalDisbursedAmount: '₹ 1,00,00,000',
        DateOfFirstDisbursement: '05-June-20',
        BranchName: 'Navrangpura',
        BranchCode: '0002051',
        DateOfRequest: '04-June-2020'
    }
];
const RequestssentToBorrower = [
    {
        Id: '1',
        BorrowerName: 'VM Shah & Co.',
        ApplicationID: 'CW-ALT-11599-10014613',
        PAN: 'HNYPS9340P',
        TypeOfFacility: 'Working Capital',
        TotalDisbursedAmount: '₹ 1,00,00,000',
        BranchName: 'Navrangpura',
        BranchCode: '0002051',
        DateOfRequest: '04-June-2020'
    },
    {
        Id: '2',
        BorrowerName: 'VM Shah & Co.',
        ApplicationID: 'CW-ALT-11599-10014613',
        PAN: 'HNYPS9340P',
        TypeOfFacility: 'Working Capital',
        TotalDisbursedAmount: '₹ 1,00,00,000',
        BranchName: 'Navrangpura',
        BranchCode: '0002051',
        DateOfRequest: '04-June-2020'
    },
    {
        Id: '3',
        BorrowerName: 'VM Shah & Co.',
        ApplicationID: 'CW-ALT-11599-10014613',
        PAN: 'HNYPS9340P',
        TypeOfFacility: 'Working Capital',
        TotalDisbursedAmount: '₹ 1,00,00,000',
        BranchName: 'Navrangpura',
        BranchCode: '0002051',
        DateOfRequest: '04-June-2020'
    }
];
const CustomerWiseBreakUpData = [
    {
        Id: '1',
        CustomerName: 'L N Fileds Pvt. Ltd.',
        State: 'Gujarat',
        TaxableValue: '₹ 40,00,000',
        InTaxableValue: '38.02%'

    },
    {
        Id: '1',
        CustomerName: 'L N Fileds Pvt. Ltd.',
        State: 'Gujarat',
        TaxableValue: '₹ 40,00,000',
        InTaxableValue: '38.02%'
    },
    {
        Id: '1',
        CustomerName: 'L N Fileds Pvt. Ltd.',
        State: 'Gujarat',
        TaxableValue: '₹ 40,00,000',
        InTaxableValue: '38.02%'
    },
    {
        Id: '1',
        CustomerName: 'L N Fileds Pvt. Ltd.',
        State: 'Gujarat',
        TaxableValue: '₹ 40,00,000',
        InTaxableValue: '38.02%'
    },
];
const MonitoringdownloadReporte = [
    {
        Id: '1',
        FileName: 'Monitoring_Report.xlsx',
        Month: 'Apr 2020',
        UpdateOn: 'N.A',
        Status: 'Updated',
    },
    {
        Id: '2',
        FileName: 'Monitoring_Report.xlsx',
        Month: 'Apr 2020',
        UpdateOn: '26-Apr-20',
        Status: 'Not Updated',
    },
    {
        Id: '3',
        FileName: 'Monitoring_Report.xlsx',
        Month: 'Apr 2020',
        UpdateOn: '26-Apr-20',
        Status: 'Updated',
    }
];

const InPrincipleApplication = [
    {
        Id: '1',
        OrganizationName: 'VM Shah Co. Pvt. Ltd.',
        ApplicationCode: 'CW-AWC-13789-9004',
        Email: 'gaurav12@gmai.com',
        Mobile: '7567621488',
        PAN: '111AAA111A',
        Status: 'In-principle',
        InprincipleDate: '25 jun 2020',
        Inprinciple: '₹ 5,00,000',
    },
    {
        Id: '2',
        OrganizationName: 'VM Shah Co. Pvt. Ltd.',
        ApplicationCode: 'CW-AWC-13789-9004',
        Email: 'gaurav12@gmai.com',
        Mobile: '7567621488',
        PAN: '111AAA111A',
        Status: 'In-principle',
        InprincipleDate: '25 jun 2020',
        Inprinciple: '₹ 5,00,000',
    },
    {
        Id: '3',
        OrganizationName: 'VM Shah Co. Pvt. Ltd.',
        ApplicationCode: 'CW-AWC-13789-9004',
        Email: 'gaurav12@gmai.com',
        Mobile: '7567621488',
        PAN: '111AAA111A',
        Status: 'In-principle',
        InprincipleDate: '25 jun 2020',
        Inprinciple: '₹ 5,00,000',
    },
    {
        Id: '4',
        OrganizationName: 'VM Shah Co. Pvt. Ltd.',
        ApplicationCode: 'CW-AWC-13789-9004',
        Email: 'gaurav12@gmai.com',
        Mobile: '7567621488',
        PAN: '111AAA111A',
        Status: 'In-principle',
        InprincipleDate: '25 jun 2020',
        Inprinciple: '₹ 5,00,000',
    },
    {
        Id: '1',
        OrganizationName: 'VM Shah Co. Pvt. Ltd.',
        ApplicationCode: 'CW-AWC-13789-9004',
        Email: 'gaurav12@gmai.com',
        Mobile: '7567621488',
        PAN: '111AAA111A',
        Status: 'In-principle',
        InprincipleDate: '25 jun 2020',
        Inprinciple: '₹ 5,00,000',
    },

];

const ProposalDetailsInPrinciple = [
    {
        ProductName: 'Covid Relief Find 2020',
        ProductStatus: 'Active',
        TypeofLoan: 'Term Loan',
        ApplicationType: 'New',
        EMI: '₹ 3,00,000',
        Tenure: '1 Year',
        ROI: '14.25 %',
        Processingfee: '10%',
    }

]
const ProposalStatusInPrinciple = [
    {
        HoldDate: '25 jun 2020',
        SanctionDate: '25 jun 2020',
        SanctionAmount: '₹ 2,50,000',
        LastDisbursementsDate: '26 july 2020',
        LastDisbusementsAmount: '₹ 1,50,000',
        TotalDisbusementsAmount: '₹ 1,50,000',
        RejectedDateReason: '26 july 2020',
        HoldDateReason: '26 july 2020',
    }
]
const BranchDetailsInPrinciple = [
    {
        ZonalOffice: 'C.G. Road',
        RegionalOffice: 'Navrangpura',
        BranchName: 'Municipal Market Branch',
        BranchCode: 'SBI3RT12348',
        BranchAddress: 'SHYAM GOKUL A BY 24,SWASTIK',
        MakerEmailid: 'manisharma.maker@bank.com',
        MakerMobileNo: '7567621489',
        CheckerEmailid: 'gauravvipani.checker@bank.com',
        CheckerMobileNo: '9789854795',
    }
];
const Constitutioncharttable = [
    {
        Id: '1',
        Constitution: 'Proprietorship',
        Amount: '₹50,00,000',
        Applications: '8,000 (28.13 %)',
    },
    {
        Id: '2',
        Constitution: 'Partnership',
        Amount: '₹50,00,000',
        Applications: '8,000 (28.13 %)',
    },
    {
        Id: '3',
        Constitution: 'Associates',
        Amount: '₹50,00,000',
        Applications: '8,000 (28.13 %)',
    },
    {
        Id: '4',
        Constitution: 'LLP',
        Amount: '₹50,00,000',
        Applications: '8,000 (28.13 %)',
    },
    {
        Id: '5',
        Constitution: 'Pvt. Ltd. Company',
        Amount: '₹50,00,000',
        Applications: '8,000 (28.13 %)',
    },
    {
        Id: '6',
        Constitution: 'Ltd. Company',
        Amount: '₹50,00,000',
        Applications: '8,000 (28.13 %)',
    },
    {
        Id: '7',
        Constitution: 'Others',
        Amount: '₹50,00,000',
        Applications: '8,000 (28.13 %)',
    },
];
const StateData =[
    {
        Id: '1',
        StateName: 'Andhra Pradesh',
        Amount: '₹50,00,000',
        Applications: '8,000 (28.13 %)',
    },
    {
        Id: '2',
        StateName: 'Arunachal Pradesh',
        Amount: '₹50,00,000',
        Applications: '8,000 (28.13 %)',
    },
    {
        Id: '3',
        StateName: 'Assam',
        Amount: '₹50,00,000',
        Applications: '8,000 (28.13 %)',
    },
    {
        Id: '4',
        StateName: 'Bihar',
        Amount: '₹50,00,000',
        Applications: '8,000 (28.13 %)',
    },
    {
        Id: '5',
        StateName: 'Chhattisgarh',
        Amount: '₹50,00,000',
        Applications: '8,000 (28.13 %)',
    },
    {
        Id: '6',
        StateName: 'Goa',
        Amount: '₹50,00,000',
        Applications: '8,000 (28.13 %)',
    },
    {
        Id: '7',
        StateName: 'Gujarat',
        Amount: '₹50,00,000',
        Applications: '8,000 (28.13 %)',
    },
    {
        Id: '8',
        StateName: 'Haryana',
        Amount: '₹50,00,000',
        Applications: '8,000 (28.13 %)',
    },
    {
        Id: '9',
        StateName: 'Himachal Pradesh',
        Amount: '₹50,00,000',
        Applications: '8,000 (28.13 %)',
    },
    {
        Id: '10',
        StateName: 'Jharkhand',
        Amount: '₹50,00,000',
        Applications: '8,000 (28.13 %)',
    },
    {
        Id: '11',
        StateName: 'Karnataka',
        Amount: '₹50,00,000',
        Applications: '8,000 (28.13 %)',
    },
    {
        Id: '12',
        StateName: 'Kerala',
        Amount: '₹50,00,000',
        Applications: '8,000 (28.13 %)',
    },
    {
        Id: '13',
        StateName: 'Madhya Pradesh',
        Amount: '₹50,00,000',
        Applications: '8,000 (28.13 %)',
    },
      {
        Id: '14',
        StateName: 'Maharashtra',
        Amount: '₹50,00,000',
        Applications: '8,000 (28.13 %)',
    },  {
        Id: '15',
        StateName: 'Manipur',
        Amount: '₹50,00,000',
        Applications: '8,000 (28.13 %)',
    },
    {
        Id: '16',
        StateName: 'Meghalaya',
        Amount: '₹50,00,000',
        Applications: '8,000 (28.13 %)',
    },
]
const BankUserData =[
    {
        Id: '1',
        UserName: 'Nikul Patel',
        UserEmail: 'Nikul.Patel@onlinepsbloans.com',
        MobileNo: '7069418009',
        UserRole: 'Admin Maker',
        City: 'Ahmedabad',
        State: 'Gujarat',
        Status: 'Active',
    },
    {
        Id: '2',
        UserName: 'Nikul Patel',
        UserEmail: 'Nikul.Patel@onlinepsbloans.com',
        MobileNo: '7069418009',
        UserRole: 'Admin Checker',
        City: 'Ahmedabad',
        State: 'Gujarat',
        Status: 'Active',
    },
    {
        Id: '3',
        UserName: 'Nikul Patel',
        UserEmail: 'Nikul.Patel@onlinepsbloans.com',
        MobileNo: '7069418009',
        UserRole: 'Head office User',
        City: 'Ahmedabad',
        State: 'Gujarat',
        Status: 'Active',
    },
    {
        Id: '4',
        UserName: 'Nikul Patel',
        UserEmail: 'Nikul.Patel@onlinepsbloans.com',
        MobileNo: '7069418009',
        UserRole: 'Regional Office User',
        City: 'Ahmedabad',
        State: 'Gujarat',
        Status: 'Active',
    },
    {
        Id: '5',
        UserName: 'Nikul Patel',
        UserEmail: 'Nikul.Patel@onlinepsbloans.com',
        MobileNo: '7069418009',
        UserRole: 'Branch Checker',
        City: 'Ahmedabad',
        State: 'Gujarat',
        Status: 'Active',
    },
]
export {
    customersData, liveMonitorData, Disbursedthroughplatform, AddedBorrowersHistory, RequestsFromBorrower, RequestssentToBorrower,
    CustomerWiseBreakUpData, MonitoringdownloadReporte, InPrincipleApplication,
    ProposalDetailsInPrinciple, BranchDetailsInPrinciple, ProposalStatusInPrinciple,
    Constitutioncharttable,StateData,BankUserData
}
